AssetManagementUI/Controllers/OrganizationsController.cs
using OrganizationModelsLibrary;
using OrgnationManagersLibrary;
using System.Web.Mvc;

namespace AssetManagementUI.Controllers
{
    public class OrganizationsController : Controller
    {
        private readonly OrganizationManager _orgnationManager = new OrganizationManager();

        // GET: Organizations
        public ActionResult Index()
        {
            var orgnationList = _orgnationManager.GetAllOrganization();
            return View(orgnationList);
        }

        [HttpGet]
        public PartialViewResult Create()
        {
            return PartialView("PartialView/Organizations/_CreatePartial");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "Id, Name, ShortName, Location, Description")] Organization aOrganization)
        {
            if (ModelState.IsValid)
            {
                bool isShortNameExist = _orgnationManager.IsShortNameExist(aOrganization.ShortName);

                if (isShortNameExist)
                {
                    ViewBag.Message = "This Organization Short Name Already Exist in Database";
                }
                else
                {
                    int successCount = _orgnationManager.Save(aOrganization);
                    if (successCount > 0)
                    {
                        ViewBag.Message = "Organation Successfully Save in Database";
                        ViewBag.Success = 1;
                    }
                    else
                    {
                        ViewBag.Message = "Organation Save Fail";
                        ViewBag.Success = 0;
                    }

                }
                return PartialView("PartialView/Organizations/_CreatePartial");

            }
            return View("Index");
            //return PartialView("PartialView/Organizations/_CreatePartial");
        }


        public JsonResult Save(Organization aOrganization)
        {
            if (ModelState.IsValid)
            {
                bool isShortNameExist = _orgnationManager.IsShortNameExist(aOrganization.ShortName);

                if (isShortNameExist)
                {
                    ViewBag.Message = "This Organization Short Name Already Exist in Database";
                }
                else
                {
                    int successCount = _orgnationManager.Save(aOrganization);
                    if (successCount > 0)
                    {

                        ViewBag.Message = "Organation Successfully Save in Database";
                        ViewBag.Success = 1;
                        return Json(successCount, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        ViewBag.Message = "Organation Save Fail";
                        ViewBag.Success = 0;
                        return Json(0, JsonRequestBehavior.AllowGet);
                    }

                }
            }
            return Json(0, JsonRequestBehavior.AllowGet);
        }

    }
}

AssetManagementUI/Views/Shared/PartialView/Organizations/_CreatePartial.cshtml
@model OrganizationModelsLibrary.Organization

@using (Ajax.BeginForm("Create", "Organizations", new AjaxOptions()
{
    HttpMethod = "POST",
   
    OnSuccess = "StudentAdded",
    OnFailure = "StudentAddFailed"
}))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ShortName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="button" id="saveButton" class="btn btn-info">
                            <span class="fa fa-save"></span> Save
                        </button>

                        <button type="reset" class="btn btn-default">
                            <span class="fa fa-refresh"></span> Reset
                        </button>
                    </div>
                </div>
                
                <div class="form-group" id="messagebox">
                    
                    
                    @if (ViewBag.Success == 1)
                    {
                        <div class="alert alert-block alert-success">
                            <button type="button" class="close" data-dismiss="alert">
                                <i class="ace-icon fa fa-check green"></i>
                            </button>
                            ViewBag.Message;
                        </div>
                    }
                    else
                    {
                        <div class="alert alert-block alert-danger">
                            <button type="button" class="close" data-dismiss="alert">
                                <i class="ace-icon fa fa-check red"></i>
                            </button>
                            @ViewBag.Message
                        </div>
                    }
                    
                </div>
            </div>
        </div>
    </div>

}